baseURL = "http://example.org/"
languageCode = "en-us"
title = "Hamel's Site"
theme = "basic"

[params]
author = "Hamel"
description = "Learning Hugo"
gh_url = "https://api.github.com/users"
gh_user = "hamelsmu"


[permalinks]
  posts = "posts/:year/:month/:slug/"
  year = "/posts/:slug/"
  month = "/posts/:slug/"

[taxonomies]
  year = "year"
  month = "month"
  tag = "tags"
  category = "categories"
